name: Test workflow triggers

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
  pull_request:

jobs:
  your_job:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "event name ${{github.event_name}}"
