name: Test cursed OIDC beacon

# Schedule run for every 5 minutes, the minimum interval allowed. GitHub seems
# to treat this as a suggestion when they're experiencing high load, letting
# around an hour elapse between jobs.
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout token
        uses: actions/checkout@v4
        with:
          sparse-checkout: oidc-token.txt
      - run: ls -a
         
