name: Test cursed OIDC beacon

# Schedule run for every 5 minutes, the minimum interval allowed. GitHub seems
# to treat this as a suggestion when they're experiencing high load, letting
# around an hour elapse between jobs.
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout token
        uses: actions/checkout@v4
        with:    
          repository: jku/extremely-dangerous-public-oidc-beacon
          ref: current-token
          path: tokendir
          sparse-checkout: oidc-token.txt
          sparse-checkout-cone-mode: false
      
      - name: Install Sigstore
        run: |
          pip install sigstore
         
      - name: Test oidc token validity
        run: |
          ls -la && ls -la tokendir
          python test.py
